Pandas - for data manipulation and analysis

In [12]:
#creating and importing data in pandas
import pandas as pd
import warnings
warnings.filterwarnings("ignore")

df = pd.read_csv("Teacher_List_Report_20260211.csv")
df.head()
# df.shape

,S.N,Organization Code,Organization Name,Full Name,Contact Number,Training,Date Of Birth
0,1,560270006,Jana Kalyan Basic School Bhangabari,Khim Bahadur Gharti,9868630150,NaN,2041-10-01
1,2,560270006,Jana Kalyan Basic School Bhangabari,Laxman Kumar Oli,9866870561,NaN,2040-01-01
2,3,560270006,Jana Kalyan Basic School Bhangabari,Angabir Sunar,9742983094,NaN,2039-01-28
3,4,560270006,Jana Kalyan Basic School Bhangabari,Netralal Gharti Magar,9847702728,NaN,2059-12-10

In [15]:
#Creating DataFrame
import pandas as pd
import numpy as np
import random

random.seed(101)
#defining realistic names
names = ['Dambar', 'Nischal', 'Tarak', 'Buddhi']
#genders corresponding to names
genders = ['Male', 'Male', 'Male', 'Male']

#generate random data
ages = [random.randint(21,25) for _ in range(4)]
marks = [random.randint(60,95) for _ in range(4)]
subjects = random.choices(['Python', 'Statistics', 'Generative AI'], k=4)

#create DataFrame
df = pd.DataFrame({
    'Name': names,
    'Gender': genders,
    'Age': ages,
    'Marks': marks,
    'Subjects': subjects
})

df

      Name Gender  Age  Marks       Subjects
0   Dambar   Male   25     89     Statistics
1  Nischal   Male   22     63  Generative AI
2    Tarak   Male   25     92     Statistics
3   Buddhi   Male   23     73  Generative AI

In [16]:
#Statistical summary of dataframe - of numeric columns
df.describe()

         Age      Marks
count   4.00   4.000000
mean   23.75  79.250000
std     1.50  13.671747
min    22.00  63.000000
25%    22.75  70.500000
50%    24.00  81.000000
75%    25.00  89.750000
max    25.00  92.000000

In [17]:
#Shape of the dataframe - rows and columns
df.shape

(4, 5)

In [18]:
# Column names in the dataframe
df.columns

Index(['Name', 'Gender', 'Age', 'Marks', 'Subjects'], dtype='object')